[tool.semantic_release]
version_variables = ["src/camdoc/__init__.py:__version__"]
branch = "main"
upload_to_pypi = false            # İstersen ileride true yaparız ve PyPI ayarları ekleriz
build_command = ""                # Paketleme yoksa boş bırak
changelog_file = "CHANGELOG.md"
commit_message = "chore(release): v{version}"
tag_format = "v{version}"